import React from "react";
import classes from "./style.module.css";
import Card from "./Card";
import search from "../../assets/search.png";
import select from "../../assets/select.png";
import standout from "../../assets/standout.png";

const Features = () => {
  return (
    <div className={classes.Features_container}>
      <Card
        logo={search}
        title="Search"
        content="Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen."
      />
      <Card
        logo={select}
        title="Select"
        content="Choose from thousands of options generated by the slogan maker that fit your needs."
      />
      <Card
        logo={standout}
        title="Stand out"
        content="Congrats on your new slogan. It's time to win the world!"
      />
    </div>
  );
};

export default Features;
